// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC7v5Xn4gTR5vEC_j5q1IKvLcyNdlsPUlg',
    appId: '1:133645146173:web:941f4b6478b6d16666b254',
    messagingSenderId: '133645146173',
    projectId: 'manajemen-state',
    authDomain: 'manajemen-state.firebaseapp.com',
    storageBucket: 'manajemen-state.firebasestorage.app',
    measurementId: 'G-WXCCD12Y0K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBxkcicK21ypeSXj_gfLrSb6uYEOZ4Tl30',
    appId: '1:133645146173:android:57a7e0bd6cd888cd66b254',
    messagingSenderId: '133645146173',
    projectId: 'manajemen-state',
    storageBucket: 'manajemen-state.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBVy6doTwg6IBoKAG1Tqj4retXJj6eJLOw',
    appId: '1:133645146173:ios:8c28cc6fe172c42866b254',
    messagingSenderId: '133645146173',
    projectId: 'manajemen-state',
    storageBucket: 'manajemen-state.firebasestorage.app',
    iosBundleId: 'com.example.manajemenState',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBVy6doTwg6IBoKAG1Tqj4retXJj6eJLOw',
    appId: '1:133645146173:ios:8c28cc6fe172c42866b254',
    messagingSenderId: '133645146173',
    projectId: 'manajemen-state',
    storageBucket: 'manajemen-state.firebasestorage.app',
    iosBundleId: 'com.example.manajemenState',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC7v5Xn4gTR5vEC_j5q1IKvLcyNdlsPUlg',
    appId: '1:133645146173:web:96f9bd01aca188ad66b254',
    messagingSenderId: '133645146173',
    projectId: 'manajemen-state',
    authDomain: 'manajemen-state.firebaseapp.com',
    storageBucket: 'manajemen-state.firebasestorage.app',
    measurementId: 'G-7B70E8P9YV',
  );
}
